# Generated by Django 5.1.4 on 2024-12-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
