# Generated by Django 5.1.4 on 2024-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_moviereview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='movie_photos/'),
        ),
    ]
